name: Deploy Mushimushi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Clone portal repository
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/pontalelab/pontalelab-site.git portal

      - name: Copy files
        run: |
          mkdir -p portal/mushimushi

          find portal/mushimushi -mindepth 1 -delete

          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            ./ portal/mushimushi/

      - name: Commit and Push
        run: |
          cd portal

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git diff --cached --quiet || git commit -m "Auto deploy mushimushi"

          git push
